project:
  type: website
  output-dir: docs
  
website:
  title: "Sa√Ød Maanan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ./teaching/teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      light: sandstone
      dark: sandstone
    css: styles.css
    toc: true
    page-layout: full

editor: visual

