project:
  type: website
  output-dir: docs
  
website:
  title: "Saïd Maanan"
  page-footer: 
    left: "Copyright &copy; 2023-2025 Saïd Maanan"
    right: "This website is built with [Quarto](https://quarto.org/)."
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    search: false
    right:
      - href: index.qmd
        text: "Home"
        icon: house-fill
      - href: publications.qmd
        text: "Research"
        icon: pc-display-horizontal
      - href: cv.qmd
        text: "Curriculum Vitae"
        icon: file-earmark-person
  cookie-consent: false

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    lang: en
    date-format: 'dddd MMMM YYYY'
    email-obfuscation: javascript
    link-external-newwindow: true
    css: styles.css
    toc: false
    page-layout: full

editor: source

resources:
  - google80a6c4ae415f3dc1.html

lightbox: auto